---
borg_version: "1.0.11"

borg_dl_url: >
  https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux{% if ansible_architecture == 'x86_64' %}64{% else %}32{% endif %}

borg_sha256: fbdc0e0d6d05a0935551f2f408f370236a76b7a30d3bb90a31c3628fe3611359

borg_path: /usr/local/bin/borg
