---
- name: Check if k9s {{ k9s_version }} is installed
  shell: k9s version || true
  register: k9s_check
  changed_when: false

- name: Install k9s
  unarchive:
    remote_src: true
    src: "{{ k9s_dl_url }}"
    dest: "{{ k9s_path | dirname }}"
    extra_opts:
      - k9s  # Extract only the binary
    owner: root
    group: root
    mode: 0755
  when: >
    k9s_check.stdout_lines | length == 0
    or k9s_version not in k9s_check.stdout_lines[0]
