---
# Usuário do sistema
# Padrão: $USER (do usuário que executa o Ansible)
# virtualbox_user: flaudisio

virtualbox_version_major: "5.2"
# VirtualBox - Ref: https://www.virtualbox.org/wiki/Linux_Downloads

virtualbox_repo_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
virtualbox_repo_line: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
virtualbox_repo_file: virtualbox

# Extension Pack - Ref: https://www.virtualbox.org/wiki/Downloads

virtualbox_extpack_version: 5.2.26
virtualbox_extpack_url: http://download.virtualbox.org/virtualbox/{{ virtualbox_extpack_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_extpack_version }}.vbox-extpack
virtualbox_extpack_dl_file: /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
