repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: git://github.com/ansible/ansible-lint.git
  rev: v4.1.0
  hooks:
    - id: ansible-lint
      files: playbook.yml
