---
- name: Atualiza cache do APT
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: pkg:update

- name: Instala pacotes básicos
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ pkg_base }}"
  tags: pkg:base

- name: Instala ferramentas de desenvolvimento
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ pkg_dev }}"
  tags: pkg:dev

- name: Instala ferramentas de administração de sistema
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ pkg_sysadmin }}"
  tags: pkg:sysadmin

- name: Instala ferramentas de gráficos e multimídia
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ pkg_media }}"
  tags: pkg:media

- name: Instala pacotes utilitários
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ pkg_misc }}"
  tags:
    - pkg:misc
    - pkg:utils

- name: Remove pacotes selecionados
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ pkg_purge }}"
  tags: pkg:purge

- name: Instala pacotes extras
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ pkg_extra.strip(',').split(',') }}"
  when: pkg_extra != ""
  tags: pkg:extra

# Git (instalado à parte por usar PPA)

- name: Habilita PPA do Git
  apt_repository:
    repo: "ppa:git-core/ppa"
    state: present
    update_cache: yes
  tags:
    - git
    - git:ppa
    - pkg:dev

- name: Instala pacotes relacionados ao Git
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - git
    - git-doc
    - git-gui
    - gitk
    - qgit
    - tig
  tags:
    - git
    - pkg:dev
