---
- name: Atualiza cache do APT
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: pkg:update

- name: Instala pacotes básicos
  apt:
    name: "{{ pkg_base }}"
    state: present
    install_recommends: false
  tags: pkg:base

- name: Instala ferramentas de desenvolvimento
  apt:
    name: "{{ pkg_dev }}"
    state: present
    install_recommends: false
  tags: pkg:dev

- name: Instala ferramentas de administração de sistema
  apt:
    name: "{{ pkg_sysadmin }}"
    state: present
    install_recommends: false
  tags: pkg:sysadmin

- name: Instala ferramentas de gráficos e multimídia
  apt:
    name: "{{ pkg_media }}"
    state: present
    install_recommends: false
  tags: pkg:media

- name: Instala pacotes utilitários
  apt:
    name: "{{ pkg_misc }}"
    state: present
    install_recommends: false
  tags:
    - pkg:misc
    - pkg:utils

- name: Remove pacotes selecionados
  apt:
    name: "{{ pkg_purge }}"
    state: absent
    purge: true
  tags: pkg:purge

- name: Instala pacotes extras
  apt:
    name: "{{ pkg_extra }}"
    state: present
    install_recommends: false
  tags: pkg:extra

# Git (instalado à parte por usar PPA)

- name: Habilita PPA do Git
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: true
  tags:
    - pkg:git
    - pkg:git:ppa
    - pkg:dev

- name: Instala pacotes relacionados ao Git
  apt:
    name:
      - git
      - git-doc
      - git-gui
      - gitk
      - qgit
      - tig
    state: present
    install_recommends: false
  tags:
    - pkg:git
    - pkg:dev
