---
# Usuário e $HOME do sistema
# Padrão: $USER e $HOME (do usuário que executa o Ansible)
# my_user: flaudisio
# my_home: /home/flaudisio

# Diretório dos dotfiles
# Padrão: $HOME/.rc (do usuário que executa o Ansible)
# dotfiles_dir: /opt/dotfiles

# Força atualização (via Git) do diretório de dotfiles
update_dotfiles: no

# Variáveis "*_packages": listas de pacotes independentes e/ou que são dependências
# de várias aplicações simultaneamente. Vários provavelmente já estarão instalados,
# mas não custa documentá-los.

# Nota: esses pacotes são instalados com *no-install-recommends*!

base_packages:
  - bash-completion
  - ca-certificates
  - cryptsetup
  - curl
  - dkms
  - exo-utils
  - less
  - software-properties-common
  - tmux
  - tree
  - wget
  - xbacklight
  - xfce4-terminal

dev_packages:
  - gedit
  - gedit-developer-plugins
  - vim

sysadmin_packages:
  - gdebi-core
  - gnome-disk-utility
  - cracklib-runtime
  - gparted
  - htop
  - iotop
  - iptraf-ng
  - lshw
  - lsof
  - mtr-tiny
  - netcat-openbsd
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - openssh-client
  - openssh-server
  - rsync
  - whois

media_packages:
  - gimp
  - pavucontrol
  - shotwell
  - vlc
  - vlc-plugin-notify

misc_packages:
  - atool
  - cups-pdf
  - system-config-printer-gnome
  - system-config-printer-udev
  - evince
  - file-roller
  - firefox
  - ipcalc
  - keepassx
  - multitail
  - p7zip
  - p7zip-full
  - p7zip-rar
  - pbzip2
  - pigz
  - remmina
  - remmina-plugin-rdp
  - remmina-plugin-vnc
  - libfreerdp-plugins-standard
  - transmission-gtk
  - unar
  - unrar
  - unzip
  - xclip
  - zenity

# Pacotes que serão removidos via 'purge'.
# TODO: verificar eventual uso do 'autoremove'.
purge_packages:
  # Xubuntu-desktop
  - gmusicbrowser
  - gnumeric
  - mousepad
  - pidgin
  # "Command not found"
  - command-not-found
  - command-not-found-data
  - python3-commandnotfound
  - sessioninstaller
  # Outros
  - xul-ext-ubufox

# Pacotes extras, para flexibilidade.
# extra_packages: "pacote1,pacote2,pacote3"
extra_packages: ""

# i3 - https://i3wm.org/docs/repositories.html
i3_keyring_deb: http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2017.01.02_all.deb
i3_repo_line: deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe
i3_repo_file: sur5r-i3

# Docker (role externa?, adicionar ansible_user_id ao grupo 'docker')
# ...

# nginx e nginx config (role externa?)
# ...

# doctl - https://github.com/digitalocean/doctl/releases
doctl_version: "1.5.0"
doctl_path: /usr/local/bin/doctl
doctl_arch: amd64

# Mattermost - https://docs.mattermost.com/install/desktop.html#linux-beta
mattermost_version: "3.6.0"

# Franz - http://meetfranz.com/#download_all

franz_version: "4.0.4"

# Terraform - https://www.terraform.io/downloads.html
terraform_version: "0.9.5"

# pip / virtualenv{,wrapper}
# ...

# rbenv - https://github.com/rbenv/rbenv#installation
rbenv_version: "0.0.0"

# jq - https://github.com/stedolan/jq/releases
jq_version: "1.5"

# ctop - https://github.com/bcicen/ctop/releases
ctop_version: "0.5.1"
