---
- name: Ensure AWS CLI is installed
  pip:
    name: awscli
    version: "{{ awscli_version }}"
    state: present
    virtualenv: "{{ awscli_install_dir }}"
    virtualenv_python: python3
    extra_args: --no-cache

- name: Ensure executable symlinks exists
  file:
    src: "{{ awscli_install_dir }}/bin/{{ item }}"
    path: "{{ awscli_symlink_dir }}/{{ item }}"
    state: link
  loop:
    - aws
    - aws_completer

- name: Configure Bash completion
  copy:
    content: |
      complete -C aws_completer aws
    dest: /etc/bash_completion.d/aws
    owner: root
    group: root
    mode: 0644
  when: awscli_enable_bash_completion
  tags: awscli:completion

- name: Ensure aws-shell is installed (if enabled)
  pip:
    name: aws-shell
    version: "{{ awscli_shell_version }}"
    state: present
    virtualenv: "{{ awscli_shell_install_dir }}"
    virtualenv_python: python3
    extra_args: --no-cache
  when: awscli_install_shell

- name: Ensure 'aws-shell' symlink exists
  file:
    src: "{{ awscli_shell_install_dir }}/bin/aws-shell"
    path: "{{ awscli_symlink_dir }}/aws-shell"
    state: link
    follow: false
    force: false
  when: awscli_install_shell
