---
- name: Cria diretório de instalação
  file:
    path: "{{ dotfiles_install_dir }}"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"
    mode: 0755

- name: Instala dotfiles
  become: true
  become_user: "{{ dotfiles_user }}"
  block:
    - name: Clona e/ou atualiza repositório
      git:
        repo: "{{ dotfiles_git_repo }}"
        dest: "{{ dotfiles_install_dir }}"
        version: "{{ dotfiles_git_version }}"
        update: "{{ dotfiles_git_update }}"

    - name: Instala dotfiles
      file:
        src: "{{ item }}"
        dest: "{{ dotfiles_home }}/.{{ item | basename }}"
        force: true
        state: link
      loop: "{{ lookup('fileglob', dotfiles_files_glob, wantlist=True) | sort }}"
