---
- name: Define variáveis de usuário e $HOME
  set_fact:
    _dotfiles_user: "{{ dotfiles_user | default(lookup('env', 'USER')) }}"
    _dotfiles_home: "{{ dotfiles_home | default(lookup('env', 'HOME')) }}"

- name: Define variável do diretório de instalação
  set_fact:
    _dotfiles_dir: "{{ dotfiles_dir | default(lookup('env', 'HOME') + '/.rc') }}"

- name: Cria diretório de instalação
  file:
    path: "{{ _dotfiles_dir }}"
    state: directory
    owner: "{{ _dotfiles_user }}"
    group: "{{ _dotfiles_user }}"
    mode: 0755

- name: Clona e/ou atualiza repositório
  git:
    repo: https://github.com/flaudisio/rc.git
    dest: "{{ _dotfiles_dir }}"
    version: master
    update: "{{ dotfiles_update }}"
  become: yes
  become_user: "{{ _dotfiles_user }}"

- name: Instala dotfiles
  file:
    src: "{{ item }}"
    dest: "{{ _dotfiles_home }}/.{{ item | basename }}"
    force: yes
    state: link
  with_fileglob:
    - "{{ _dotfiles_dir }}/dotfiles/*"
  become: yes
  become_user: "{{ _dotfiles_user }}"
