---
- name: Atualiza cache do APT
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: pkg:update

- name: Instala pacotes básicos
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ base_packages }}"
  tags: pkg:base

- name: Instala ferramentas de desenvolvimento
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ dev_packages }}"
  tags: pkg:dev

- name: Instala ferramentas de administração de sistema
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ sysadmin_packages }}"
  tags: pkg:sysadmin

- name: Instala ferramentas de gráficos e multimídia
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ media_packages }}"
  tags: pkg:media

- name: Instala pacotes utilitários
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ misc_packages }}"
  tags:
    - pkg:misc
    - pkg:utils

- name: Remove pacotes selecionados
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ purge_packages }}"
  tags: pkg:purge

- name: Instala pacotes extras
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items: "{{ extra_packages.strip(',').split(',') }}"
  tags: pkg:extra
  when: extra_packages != ""

# Git (instalado à parte por usar PPA)

- name: Habilita PPA do Git
  apt_repository:
    repo: "ppa:git-core/ppa"
    state: present
    update_cache: yes
  tags:
    - git
    - git:ppa
    - pkg:dev

- name: Instala pacotes relacionados ao Git
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - git
    - git-doc
    - git-gui
    - qgit
    - tig
  tags:
    - git
    - pkg:dev
