---
- name: Verifica se Franz {{ franz_version }} está instalado
  stat:
    path: "{{ franz_install_dir }}"
  register: franz_check

- name: Cria diretório de instalação
  file:
    path: "{{ franz_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not franz_check.stat.exists

- name: Baixa e extrai Franz
  unarchive:
    remote_src: true
    src: https://github.com/meetfranz/franz-app/releases/download/{{ franz_version }}/Franz-linux-x64-{{ franz_version }}.tgz
    dest: "{{ franz_install_dir }}"
    owner: root
    group: root
  when: not franz_check.stat.exists

- name: Configura link simbólico do executável
  alternatives:
    name: franz
    path: "{{ franz_install_dir }}/Franz"
    link: /usr/bin/franz

- name: Configura arquivo .desktop
  template:
    src: Franz.desktop.j2
    dest: /usr/share/applications/Franz.desktop
    owner: root
    group: root
    mode: 0644

- name: Configura ícone do aplicativo
  copy:
    src: franz.png
    dest: /usr/share/icons/hicolor/512x512/apps/franz.png
    owner: root
    group: root
    mode: 0644
