---
# yamllint disable rule:line-length

awsvault_version: 4.6.4

awsvault_dl_url: >-
  https://github.com/99designs/aws-vault/releases/download/v{{ awsvault_version }}/aws-vault-linux-amd64

awsvault_path: /usr/local/bin/aws-vault
