---
- name: Verifica se restic {{ restic_version }} está instalado
  shell: restic version || true
  register: restic_check
  changed_when: false

- name: Baixa arquivo comprimido
  get_url:
    url: "{{ restic_dl_url }}"
    dest: /tmp/restic.bz2
    checksum: sha256:{{ restic_sha256_checksum }}
    owner: root
    group: root
    mode: 0644
  when: >
    restic_check.stdout_lines | length == 0
    or restic_version not in restic_check.stdout_lines[0]

- name: Instala binário
  shell: >
    bzip2 --decompress --stdout /tmp/restic.bz2 > {{ restic_path }}
  when: >
    restic_check.stdout_lines | length == 0
    or restic_version not in restic_check.stdout_lines[0]

- name: Assegura permissões do executável
  file:
    path: "{{ restic_path }}"
    state: file
    owner: root
    group: root
    mode: 0755

- name: Configura Bash completion
  command: >
    restic generate --bash-completion /etc/bash_completion.d/restic
  when: >
    restic_check.stdout_lines | length == 0
    or restic_version not in restic_check.stdout_lines[0]
  tags: restic:completion
