---
# Global

desktop_user: "{{ lookup('ENV', 'USER') }}"
desktop_home_dir: "{{ lookup('ENV', 'HOME') }}"
desktop_config_dir: "{{ desktop_home_dir }}/.config"

# Autostart

desktop_autostart_dir: "{{ desktop_config_dir }}/autostart"

desktop_autostart_disable_apps:
  - blueman
  - update-notifier

# User dirs

desktop_user_dirs_base_dir: "{{ desktop_home_dir }}"

desktop_user_dirs:
  - name: DESKTOP
    path: Desktop
  - name: DOWNLOAD
    path: cache
  - name: TEMPLATES
    path: library/Templates
  - name: PUBLICSHARE
    path: library/Public
  - name: DOCUMENTS
    path: library/Documents
  - name: MUSIC
    path: library/Music
  - name: PICTURES
    path: library/Pictures
  - name: VIDEOS
    path: library/Videos

desktop_user_dirs_remove_default_dirs: false

# Bookmarks

desktop_bookmarks_file: "{{ desktop_config_dir }}/gtk-3.0/bookmarks"

desktop_bookmarks:
  - /arquivos
  - "{{ desktop_home_dir }}/cache"

# Xfconf

desktop_xfconf_settings:
  - channel: xsettings
    property: /Gtk/DecorationLayout
    value: close,maximize,minimize:menu
    value_type: string

# Keyboard shortcuts
# See 'defaults/main/keyboard-shortcuts.yml'.
