---
# Global

desktop_user: "{{ lookup('ENV', 'USER') }}"
desktop_home_dir: "{{ lookup('ENV', 'HOME') }}"
desktop_config_dir: "{{ desktop_home_dir }}/.config"

# Autostart

desktop_autostart_dir: "{{ desktop_config_dir }}/autostart"

desktop_autostart_disable_apps:
  - blueman
  - update-notifier
