---
- name: Verifica se MEGAsync está instalado
  shell: dpkg-query --showformat='${Version}' --show megasync || true
  register: megasync_check
  changed_when: false

- name: Instala MEGAsync
  block:
  - name: Instala chave do repositório
    apt_key:
      url: "{{ megasync_repo_key_url }}"
      state: present
      keyring: /etc/apt/trusted.gpg.d/megasync.gpg

  - name: Instala pacote do MEGAsync
    apt:
      deb: "{{ megasync_package_url }}"
      state: present
    install_recommends: false
  when: "'no packages found matching' in megasync_check.stderr"
