---
- name: Verifica se MEGAsync está instalado
  shell: dpkg-query --showformat='${Version}' --show megasync || true
  register: megasync_check
  changed_when: false

- name: Instala MEGAsync
  apt:
    deb: https://mega.nz/linux/MEGAsync/xUbuntu_16.04/amd64/megasync-xUbuntu_16.04_amd64.deb
    state: present
    install_recommends: no
  when: "'no packages found matching' in megasync_check.stderr"
