---
- name: Instala chave do repositório
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ spotify_repo_key }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg

- name: Configura repositório
  apt_repository:
    repo: "{{ spotify_repo_line }}"
    filename: "{{ spotify_repo_file }}"
    state: present
    update_cache: true

- name: Instala Spotify
  apt:
    name:
      - spotify-client
      - libavcodec-extra
    state: present
    install_recommends: false
