---
- name: Cria diretório ~/.config
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Configura i3 e i3status
  copy:
    src: "{{ item }}/"
    dest: "{{ lookup('env', 'HOME') }}/.config/{{ item }}/"
  with_items:
    - i3
    - i3status
