---
# Formato de versão do pacote: "X.Y.Z-AA"
# Exemplo: "4.0.0-43"
- name: Verifica se Mattermost {{ mattermost_version }} está instalado
  shell: dpkg-query --showformat='${Version}' --show mattermost-desktop || true
  register: mattermost_check
  changed_when: false

- name: Instala Mattermost
  apt:
    deb: https://releases.mattermost.com/desktop/{{ mattermost_version }}/mattermost-desktop-{{ mattermost_version }}-linux-amd64.deb
    state: present
  when: mattermost_version not in mattermost_check.stdout.split('-')
