---
- name: Verifica se Slack está instalado
  shell: dpkg-query --showformat='${Version}' --show slack-desktop || true
  register: slack_check
  changed_when: false

- name: Instala Slack
  apt:
    deb: "{{ slack_package_url }}"
    state: present
    install_recommends: false
  when: slack_check.stdout != slack_version
