---
# O Chrome é instalado via download direto do .deb porque ele mantém um cron
# ("/opt/google/chrome/cron/google-chrome") que manipula diretamente o arquivo
# "/etc/apt/sources.list.d/google-chrome.list". Logo, prefiro não manipular
# a configuração do repositório pelo Ansible.

- name: Verifica se Chrome está instalado
  shell: dpkg-query --show google-chrome-stable || true
  register: check_chrome
  changed_when: false

- name: Define variável de status de instalação do Chrome
  set_fact:
    chrome_not_installed: 1
  when: "'no packages found matching' in check_chrome.stderr"

# Tarefas de instalação
- include: install-deb.yml
  when: chrome_not_installed is defined

# O Chrome sobrepõe os padrões dos alternatives '*-www-browser'
# (aparentemente ele se considera o último biscoito do pacote).
- name: Configura alternatives de '*-www-browser' para o Firefox
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/firefox
  with_items:
    - gnome-www-browser
    - x-www-browser
