---
- name: Verifica se Chrome está instalado
  shell: dpkg-query --show google-chrome-stable || true
  register: chrome_check
  changed_when: false

# O Chrome é instalado via download direto do .deb porque ele mantém um cron
# ("/opt/google/chrome/cron/google-chrome") que manipula diretamente o arquivo
# "/etc/apt/sources.list.d/google-chrome.list". Logo, prefiro não manipular
# a configuração do repositório pelo Ansible.
- name: Instala Chrome
  apt:
    deb: "{{ chrome_package_url }}"
    state: present
    install_recommends: false
  when: "'no packages found matching' in chrome_check.stderr"

# O Chrome sobrepõe os padrões dos alternatives '*-www-browser'
- name: Reverte alternatives de '*-www-browser' para o Firefox
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/firefox
  loop:
    - gnome-www-browser
    - x-www-browser
  when: not chrome_set_as_default_browser
