---
- name: Instala chave do reposit칩rio
  apt_key:
    url: "{{ virtualbox_repo_key_url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
  tags:
    - virtualbox:repo
    - virtualbox:install

- name: Configura reposit칩rio
  apt_repository:
    repo: "{{ virtualbox_repo_line }}"
    filename: "{{ virtualbox_repo_file }}"
    state: present
    update_cache: true
  tags:
    - virtualbox:repo
    - virtualbox:install

- name: Instala VirtualBox
  apt:
    name:
      - virtualbox-{{ virtualbox_version_major }}
      - libsdl-ttf2.0-0
    state: present
    install_recommends: false
  tags: virtualbox:install

- name: Adiciona usu치rio ao grupo 'vboxusers'
  user:
    name: "{{ virtualbox_user }}"
    groups: vboxusers
    append: true
  tags: virtualbox:install

- name: Verifica se Extension Pack est치 instalado
  shell: >
    set -o pipefail &&
    vboxmanage list extpacks | grep '^Version:.*{{ virtualbox_extpack_version }}$'
  register: virtualbox_check_extpack
  failed_when: virtualbox_check_extpack.rc > 1
  changed_when: false
  tags: virtualbox:extpack

- name: Baixa Extension Pack
  get_url:
    url: "{{ virtualbox_extpack_url }}"
    dest: "{{ virtualbox_extpack_dl_file }}"
  when: virtualbox_check_extpack.rc == 1
  tags: virtualbox:extpack

- name: Instala Extension Pack
  shell: >
    set -o pipefail &&
    echo yes | vboxmanage extpack install --replace {{ virtualbox_extpack_dl_file }}
  when: virtualbox_check_extpack.rc == 1
  tags: virtualbox:extpack
