---
- name: Verifica se Terraform {{ terraform_version }} está instalado
  shell: terraform version || true
  register: terraform_check
  changed_when: false

- name: Instala Terraform
  unarchive:
    remote_src: true
    src: "{{ terraform_dl_url }}"
    dest: "{{ terraform_path | dirname }}"
    owner: root
    group: root
    mode: 0755
  when: >
    terraform_check.stdout_lines | length == 0
    or terraform_version not in terraform_check.stdout_lines[0]
