---
- name: Configura sysctl
  sysctl:
    name: vm.swappiness
    value: 10
    sysctl_file: /etc/sysctl.d/90-ansible-workstation.conf
    state: present
    reload: yes
  tags: base:sysctl

- name: Configura alternatives
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - name: editor
      path: /usr/bin/vim.basic
    - name: x-cursor-theme
      path: /usr/share/icons/DMZ-Black/cursor.theme
  tags: base:alternatives
