---
- name: Verifica se q {{ q_version }} está instalado
  shell: q --version || true
  register: q_check
  changed_when: false

- name: Instala q
  get_url:
    url: "{{ q_dl_url }}"
    dest: "{{ q_path }}"
    force: true
    owner: root
    group: root
    mode: 0755
  when: >
    q_check.stderr_lines | length == 0
    or q_version not in q_check.stderr_lines[0]
