---
- name: Configura paths
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - name: editor
      path: /usr/bin/vim.basic
    - name: x-cursor-theme
      path: /usr/share/icons/DMZ-Black/cursor.theme
