---
- name: Check if Albert is installed
  shell: dpkg-query --showformat='${Version}' --show albert || true
  register: albert_check
  changed_when: false

- name: Run installation tasks
  when: albert_check.stdout_lines | length == 0
  block:
    # We use 'get_url' instead of just 'apt_key' because without the 'Accept'
    # header we get a 404 error.
    - name: Get repository key
      get_url:
        url: "{{ albert_repo_key_url }}"
        dest: /tmp/albert-pubkey
        force: true
        headers:
          Accept: "*/*"

    - name: Install repository key
      apt_key:
        file: /tmp/albert-pubkey
        state: present
        keyring: /etc/apt/trusted.gpg.d/albert.gpg

    - name: Ensure repository is configured
      apt_repository:
        repo: "{{ albert_repo_line }}"
        filename: "{{ albert_repo_file }}"
        state: present
        update_cache: true

    - name: Install Albert
      apt:
        name: albert
        state: present
        install_recommends: false
