---
- name: Instala chave do repositório PGDG
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8
    state: present

- name: Configura repositório do PGDG
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    filename: pgdg
    state: present
    update_cache: yes
