---
- name: Workstation - Services
  hosts: all

  roles:
    - role: docker
      tags: docker

  post_tasks:
    - name: Install Docker Compose completion
      get_url:
        # yamllint disable-line rule:line-length
        url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose
        owner: root
        group: root
        mode: 0644
      when: docker_install_compose | bool
      tags:
        - docker
        - docker:compose
